version: '3.7'
services:
  # Golang backend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - redis
      - firebase
    environment:
      - ENV=development
      - PORT=8080
      # - REDIS_HOST=redis:6379
      # - REDIS_USER=default
      # - REDIS_PASS=IMZZZwi63WHSFV5MJ
      - FIREBASE_AUTH_EMULATOR_HOST=firebase:9099
      - FIRESTORE_EMULATOR_HOST=firebase:8088
      - FIREBASE_PROJECT_ID=demo-tricktakersclub
      - FIREBASE_API_KEY=demo-api-key
      - BROWSER_ORIGIN=http://localhost:5173
    image: backend
    ports:
      - "8080:8080"

  # React app bootstrapped with Vite and served with Nginx
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      args:
        - FIREBASE_AUTH_EMULATOR_HOST=http://127.0.0.1:9099
        - FIREBASE_API_KEY=demo-api-key
        - FIREBASE_AUTH_DOMAIN=demo-tricktakersclub.firebaseapp.com
        - FIREBASE_PROJECT_ID=demo-tricktakersclub
        - FIREBASE_STORAGE_BUCKET=demo-tricktakersclub.appspot.com
        - FIREBASE_MESSAGING_SENDER_ID=demo-messageing-sender-id
        - FIREBASE_APP_ID=demo-app-id
        - FIREBASE_MEASUREMENT_ID=demo-measurement-id
        - BACKEND_HOST=http://localhost:8080
    depends_on:
      - backend
    image: frontend
    ports:
      - "5173:5173"

  # Redis Database
  redis:
    command: [
      "redis-server",
      "--loglevel warning",
      "--user default on >IMZZZwi63WHSFV5MJ ~* &* +@all",
    ]
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

  # Firebase emulator
  firebase:
    build: 
      dockerfile: Dockerfile
      context: ./firebase
    volumes:
      - firebase-data:/app
    ports:
      - "127.0.0.1:9099:9099" # auth
      - "127.0.0.1:8088:8088" # firestore
      - "127.0.0.1:4000:4000" # ui


volumes:
  redis-data:
    driver: local
  firebase-data:
    driver: local