version: '3.7'
services:
  # LOCAL PROXY
  local-proxy:
    build:
      context: ./local-proxy
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - core
      - play
    image: local-proxy
    ports:
      - "80:80"
  
  # CORE SERVICE
  core:
    build:
      context: ./backend
      dockerfile: Dockerfile.core
    depends_on:
      - firebase
    environment:
      - ENV=development
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=password
      - FIREBASE_AUTH_EMULATOR_HOST=firebase:9099
      - FIRESTORE_EMULATOR_HOST=firebase:8088
      - FIREBASE_PROJECT_ID=demo-tricktakersclub
      - FIREBASE_API_KEY=demo-api-key
      - ALLOWED_ORIGIN=http://localhost:5173
      - ABLY_API_KEY=${ABLY_DEV_API_KEY}
      - SERVER_WORKER_TIMEOUT=1800s
    image: core
    ports:
      - "8080:8080"

  # PLAY SERVICE
  play:
    build:
      context: ./backend
      dockerfile: Dockerfile.play
    depends_on:
      - firebase
      - redis
    environment:
      - ENV=development
      - PORT=7070
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=password
      - FIREBASE_AUTH_EMULATOR_HOST=firebase:9099
      - FIRESTORE_EMULATOR_HOST=firebase:8088
      - FIREBASE_PROJECT_ID=demo-tricktakersclub
      - FIREBASE_API_KEY=demo-api-key
      - ALLOWED_ORIGIN=http://localhost
    image: play
    ports:
      - "7070:7070"

  # FRONTEND SERVICE
  frontend:
    depends_on:
      - firebase
    image: node:alpine
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    working_dir: /frontend
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - VITE_FIREBASE_AUTH_EMULATOR_HOST=http://127.0.0.1:9099
      - VITE_FIREBASE_API_KEY=demo-api-key
      - VITE_FIREBASE_AUTH_DOMAIN=demo-tricktakersclub.firebaseapp.com
      - VITE_FIREBASE_PROJECT_ID=demo-tricktakersclub
      - VITE_FIREBASE_STORAGE_BUCKET=demo-tricktakersclub.appspot.com
      - VITE_FIREBASE_MESSAGING_SENDER_ID=demo-messaging-sender-id
      - VITE_FIREBASE_APP_ID=demo-app-id
      
  # REDIS SERVICE
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --loglevel warning --requirepass "password"

  # FIREBASE EMULATOR
  firebase:
    build: 
      dockerfile: Dockerfile
      context: ./firebase
    volumes:
      - firebase-data:/app
    ports:
      - "127.0.0.1:9099:9099" # auth
      - "127.0.0.1:8088:8088" # firestore
      - "127.0.0.1:4000:4000" # ui


volumes:
  firebase-data:
    driver: local
  redis-data:
    driver: local
  node_modules:
    driver: local
