version: '3.7'
services:
  # Golang backend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - play-cache
    image: backend
    ports:
      - "8080:8080"

  # React app bootstrapped with Vite and served with Nginx
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - backend
    image: frontend
    ports:
      - "5173:5173"

  # Redis Database
  play-cache:
    command: [
      "redis-server",
      "--loglevel warning",
      "--user default on >IMZZZwi63WHSFV5MJ^wiDt@z781r%SAX ~* &* +@all",
    ]
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - play-cache:/data


volumes:
  play-cache:
    driver: local