version: '3.7'
services:
  # Golang backend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - redis-data
      - firebase
    image: backend
    ports:
      - "8080:8080"

  # React app bootstrapped with Vite and served with Nginx
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - backend
    image: frontend
    ports:
      - "5173:5173"

  # Redis Database
  redis:
    command: [
      "redis-server",
      "--loglevel warning",
      "--user default on >IMZZZwi63WHSFV5MJ^wiDt@z781r%SAX ~* &* +@all",
    ]
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

  # Firebase emulator
  firebase:
    build: 
      dockerfile: Dockerfile
      context: ./firebase
    volumes:
      - firebase-data:/app
    ports:
      - "127.0.0.1:9099:9099" # auth
      - "127.0.0.1:4000:4000" # ui


volumes:
  redis-data:
    driver: local
  firebase-data:
    driver: local