version: '3.7'
services:
  # Golang backend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - firebase
    environment:
      - ENV=development
      - PORT=8080
      - FIREBASE_AUTH_EMULATOR_HOST=firebase:9099
      - FIRESTORE_EMULATOR_HOST=firebase:8088
      - FIREBASE_PROJECT_ID=demo-tricktakersclub
      - FIREBASE_API_KEY=demo-api-key
      - BROWSER_ORIGIN=http://localhost:5173
      - ABLY_API_KEY=${ABLY_DEV_API_KEY}
      - SERVER_WORKER_TIMEOUT=1800s
    image: backend
    ports:
      - "8080:8080"

  # React app bootstrapped with Vite and served with Nginx
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      args:
        - FIREBASE_AUTH_EMULATOR_HOST=http://127.0.0.1:9099
        - FIREBASE_API_KEY=demo-api-key
        - FIREBASE_AUTH_DOMAIN=demo-tricktakersclub.firebaseapp.com
        - FIREBASE_PROJECT_ID=demo-tricktakersclub
        - FIREBASE_STORAGE_BUCKET=demo-tricktakersclub.appspot.com
        - FIREBASE_MESSAGING_SENDER_ID=demo-messageing-sender-id
        - FIREBASE_APP_ID=demo-app-id
        - FIREBASE_MEASUREMENT_ID=demo-measurement-id
        - BACKEND_HOST=http://localhost:8080
    depends_on:
      - backend
    image: frontend
    ports:
      - "5173:5173"

  # Firebase emulator
  firebase:
    build: 
      dockerfile: Dockerfile
      context: ./firebase
    volumes:
      - firebase-data:/app
    ports:
      - "127.0.0.1:9099:9099" # auth
      - "127.0.0.1:8088:8088" # firestore
      - "127.0.0.1:4000:4000" # ui


volumes:
  firebase-data:
    driver: local