version: '3.7'
services:
  # Golang backend
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    image: backend
    ports:
      - "8080:8080"

  # React app bootstrapped with Vite and served with Nginx
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    depends_on:
      - backend
    image: frontend
    ports:
      - "5173:5173"