name: Automated Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  changes:
    name: Files Changed
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      core: ${{ steps.filter.outputs.core }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - "frontend/**"
            core:
              - "backend/core/**"

  frontend-tests:
    name: Frontend Tests
    needs: changes
    runs-on: ubuntu-latest
    # Only run if the frontend code has changed
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Run Vitest
        working-directory: ./frontend
        run: npm run test

  core-tests:
    name: Core Service Tests
    needs: changes
    runs-on: ubuntu-latest
    # Only run if the core service code has changed
    if: ${{ needs.changes.outputs.core == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build
        working-directory: ./backend/core
        run: go build -v -o ./...

      - name: Test
        working-directory: ./backend/core
        run: go test -v ./...
