name: Backend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build
        working-directory: ./backend
        run: go build -v -o ./...

      - name: Test
        working-directory: ./backend
        run: go test -v ./...
