name: Go

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/go-tests.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/go-tests.yml"

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build
        working-directory: ./backend
        run: go build -v -o ./...

      - name: Test
        working-directory: ./backend
        run: go test -v -o ./...
